use_frameworks!

target 'BillboardSwiftLibrary_Example' do
  pod 'BillboardSwiftLibrary', :path => '../'
  pod 'FTIndicator'

  target 'BillboardSwiftLibrary_Tests' do
    inherit! :search_paths

  end
end
